# fly.toml app configuration file generated for table-app on 2025-01-08T10:59:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'table-app'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_count = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
